{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "watch", "delete", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role-binding
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: s3-csi-driver-controller-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-cluster-role-binding
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-controller-mountpoint-claim-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
